Implement add() function for matrices

diff --git a/program1_matrices/matrix b/program1_matrices/matrix
--- a/program1_matrices/matrix
+++ b/program1_matrices/matrix
@@ -173,6 +173,82 @@ mean() {
   done
 }
 
+# Takes in 2 M-by-N matrices and prints a M-by-N matrix formed by adding the two
+# input matrices
+#
+# SYNOPSIS
+#   add MATRIX_LEFT MATRIX_RIGHT
+#
+# ARGUMENTS
+#   MATRIX_LEFT - a string of EOL-separated rows, each contains an equal number
+#  of tab-separated integers.
+#   MATRIX_RIGHT - a string of EOL-separated rows, each contains an equal number
+#  of tab-separated integers
+#
+# NOTES
+#   Assume  MATRIX_LEFT  and  MATRIX_RIGHT  have the same number of rows and
+#  the same number of columns.
+#
+# RETURNS
+#   None
+add() {
+  # ensure there are exactly 2 arguments
+  if [[ "$#" -ne 2 ]]; then
+    echo 'Usage: ./matrix add MATRIX_LEFT MATRIX_RIGHT' >&2
+    return 1
+  # ensure the files exist
+  elif [[ ! -f "$1" ]] || [[ ! -f "$2" ]]; then
+    echo 'Could not read file(s)' >&2
+    return 1
+  # ensure both matrices have the same dimensions
+  elif [[ "$(dims "$1")" != "$(dims "$2")" ]]; then
+    echo 'Invalid matrix summation' >&2
+    return 1
+  fi
+
+  declare -A matleft
+  declare -A matright
+  local dimensions=($(dims "$1"))
+  local num_rows="${dimensions[0]}"
+  local num_cols="${dimensions[1]}"
+
+  # read the left-hand-side matrix
+  local i=0
+  while read row; do
+    # echo "Row is: ${row}"
+    row=(${row})
+    for ((j=0;j<num_cols;j++)); do
+      matleft["${i}","${j}"]="${row["${j}"]}"
+    done
+    ((i++))
+  done < "$1"
+
+  # read the right-hand-side matrix
+  i=0
+  while read row; do
+    row=(${row})
+    for ((j=0;j<num_cols;j++)); do
+      matright["${i}","${j}"]="${row["${j}"]}"
+    done
+    ((i++))
+  done < "$2"
+
+  # add two matrices and print results
+  for ((i=0;i<num_rows;i++)); do
+    for ((j=0;j<num_cols;j++)); do
+      local left="${matleft["${i}","${j}"]}"
+      local right="${matright["${i}","${j}"]}"
+
+      printf "%d" "$(expr "${left}" + "${right}")"
+
+      if [[ "${j}" -lt "$(expr "${num_cols}" - 1)" ]]; then
+        printf "\t"
+      fi
+    done
+    printf "\n"
+  done
+}
+
 trap "rm -f fin$$" INT HUP TERM
 
 # TODO: validate command line arguments and use  $1 "${@:2}"  instead of using case
@@ -185,6 +261,9 @@ case "$1" in
     ;;
   'mean')
     mean "${@:2}"
+    ;;
+  'add')
+    add "${@:2}"
     ;;
   *)
     echo 'Invalid argument. Usage:' >&2
