Improve comments and fix bugs in transpose()

diff --git a/program1_matrices/matrix b/program1_matrices/matrix
--- a/program1_matrices/matrix
+++ b/program1_matrices/matrix
@@ -1,5 +1,5 @@
 #!/bin/bash
-#
+
 # matrix
 #
 # Phi Luu
@@ -21,11 +21,12 @@
 # RETURNS
 #   The rounded result to the nearest integer and away from 0.
 round_div() {
+  # just a fail safe to make sure there are two numbers
   if [[ "$#" -ne 2 ]] || [[ -z "$1" ]] || [[ -z "$2" ]]; then
     return 1
   fi
 
-  # formula provided by Brewster
+  # formula provided by Prof. Ben Brewster
   _RET="$((($1 + ($2 / 2) * (2 * ($1 > 0) - 1 )) / $2))"
 }
 
@@ -42,18 +43,19 @@ round_div() {
 # RETURNS
 #   None
 dims() {
+  # temporary file name in case of reading from stdin
   local fin="fin$$"
 
   # ensure there is at most 1 argument
   if [[ "$#" -gt 1 ]]; then
     echo 'Usage: ./matrix dims [MATRIX]' >&2
-    return 1
+    exit 1
   fi
   # if using file, ensure the file exists
   if [[ "$#" -eq 1 ]]; then
     if [[ ! -f "$1" ]]; then
       echo 'Could not read file' >&2
-      return 1
+      exit 1
     else
       fin="$1"
     fi
@@ -65,9 +67,9 @@ dims() {
   # read the first row of matrix as an array
   read -a header < "${fin}"
 
-  # count the number of rows
+  # count the number of rows = number of newline characters
   local num_rows="$(wc -l < "${fin}")"
-  # count the number of columns = num of elements in the header row
+  # count the number of columns = number of elements in the header row
   local num_cols="${#header[@]}"
 
   printf "%d %d\n" "${num_rows}" "${num_cols}"
@@ -87,18 +89,19 @@ dims() {
 # RETURNS
 #   None
 transpose() {
+  # temporary file name in case of reading from stdin
   local fin="fin$$"
 
   # ensure there is at most 1 argument
   if [[ "$#" -gt 1 ]]; then
     echo 'Usage: ./matrix transpose [MATRIX]' >&2
-    return 1
+    exit 1
   fi
   # if using file, ensure the file exists
   if [[ "$#" -eq 1 ]]; then
     if [[ ! -f "$1" ]]; then
       echo 'Could not read file' >&2
-      return 1
+      exit 1
     else
       fin="$1"
     fi
@@ -111,9 +114,45 @@ transpose() {
   read -a header < "${fin}"
   local num_cols="${#header[@]}"
 
-  # loop through the columns and transpose each of them
-  for ((i=1;i<=num_cols;i++)); do
-    printf "%s\n" "$(cut -f "${i}" "${fin}" | column)"
+  # # loop through the columns and transpose each of them
+  # for ((i=1;i<=num_cols;i++)); do
+  #   printf "%s\n" "$(cut -f "${i}" "${fin}" | column)"
+  # done
+
+  # use the dims() function to get dimensions of the matrix
+  local dimensions=($(dims "${fin}"))
+  local num_rows="${dimensions[0]}"
+  local num_cols="${dimensions[1]}"
+
+  # use associative arrays as pseudo-multidimensional arrays
+  declare -A mat
+
+  # read the matrix
+  local i=0
+  while read row; do
+    # convert string to array for instant and easy access
+    row=(${row})
+
+    # read each element of the current row to matrix
+    for ((j=0;j<num_cols;j++)); do
+      mat["${i}","${j}"]="${row["${j}"]}"
+    done
+
+    ((i++))
+  done < "${fin}"
+
+  # transpose the matrix by reading it column-first
+  for ((j=0;j<num_cols;j++)); do
+    for ((i=0;i<num_rows;i++)); do
+      # print with correct format
+      printf "%d" "${mat["${i}","${j}"]}"
+      
+      if [[ "${i}" -lt "$(expr "${num_rows}" - 1)" ]]; then
+        printf "\t"
+      fi
+    done
+    
+    printf "\n"
   done
 }
 
@@ -130,18 +169,19 @@ transpose() {
 # RETURNS
 #   None
 mean() {
+  # temporary file name in case of reading from stdin
   local fin="fin$$"
 
   # ensure there is at most 1 argument
   if [[ "$#" -gt 1 ]]; then
     echo 'Usage: ./matrix mean [MATRIX]' >&2
-    return 1
+    exit 1
   fi
   # if using file, ensure the file exists
   if [[ "$#" -eq 1 ]]; then
     if [[ ! -f "$1" ]]; then
-      echo 'Could not read file' >& 2
-      return 1
+      echo 'Could not read file' >&2
+      exit 1
     else
       fin="$1"
     fi
@@ -158,11 +198,13 @@ mean() {
   for ((i=1;i<=num_cols;i++)); do
     local col="$(cut -f "${i}" "${fin}" | column)"
 
-    # get the mean of the current column
+    # get the sum of the current column
     local sum=0
     for num in ${col}; do
       ((sum+=num))
     done
+
+    # calculate the average and round it away from zero (0.5 rounds to 1)
     round_div "${sum}" "${num_rows}"
     local avg="${_RET}"
 
@@ -194,21 +236,24 @@ add() {
   # ensure there are exactly 2 arguments
   if [[ "$#" -ne 2 ]]; then
     echo 'Usage: ./matrix add MATRIX_LEFT MATRIX_RIGHT' >&2
-    return 1
+    exit 1
   fi
   # ensure the files exist
   if [[ ! -f "$1" ]] || [[ ! -f "$2" ]]; then
     echo 'Could not read file(s)' >&2
-    return 1
+    exit 1
   fi
-  # ensure both matrices have the same dimensions
+  # ensure both matrices have the exact same dimensions
   if [[ "$(dims "$1")" != "$(dims "$2")" ]]; then
     echo 'Invalid matrix dimensions. Require two M x N matrices' >&2
-    return 1
+    exit 1
   fi
 
-  declare -A lhs
-  declare -A rhs
+  # use associative arrays as pseudo-multidimensional arrays
+  declare -A lhs  # left-hand-side matrix
+  declare -A rhs  # right-hand-side matrix
+
+  # use the dims() function to get dimensions of the matrices
   local dimensions=($(dims "$1"))
   local num_rows="${dimensions[0]}"
   local num_cols="${dimensions[1]}"
@@ -216,25 +261,32 @@ add() {
   # read the left-hand-side matrix
   local i=0
   while read row; do
-    # echo "Row is: ${row}"
+    # convert string to array for instant and easy access
     row=(${row})
+
+    # read each element of the current row to matrix
     for ((j=0;j<num_cols;j++)); do
       lhs["${i}","${j}"]="${row["${j}"]}"
     done
+
     ((i++))
   done < "$1"
 
   # read the right-hand-side matrix
   i=0
   while read row; do
+    # convert string to array for instant and easy access
     row=(${row})
+
+    # read each element of the current row to matrix
     for ((j=0;j<num_cols;j++)); do
       rhs["${i}","${j}"]="${row["${j}"]}"
     done
+
     ((i++))
   done < "$2"
 
-  # add two matrices and print results
+  # add two matrices and print results with correct format
   for ((i=0;i<num_rows;i++)); do
     for ((j=0;j<num_cols;j++)); do
       printf "%d" "$(expr "${lhs["${i}","${j}"]}" + "${rhs["${i}","${j}"]}")"
@@ -265,24 +317,30 @@ multiply() {
   # ensure there are exactly 2 arguments
   if [[ "$#" -ne 2 ]]; then
     echo 'Usage: ./matrix multiply MATRIX_LEFT MATRIX_RIGHT' >&2
-    return 1
+    exit 1
   fi
   # ensure the files exist
   if [[ ! -f "$1" ]] || [[ ! -f "$2" ]]; then
     echo 'Could not read file(s)' >&2
-    return 1
+    exit 1
   fi
+
+  # use dims() function to get the dimensions of the matrices
   local lhs_dim=($(dims "$1"))
   local rhs_dim=($(dims "$2"))
   # ensure the left-hand-side matrix has the same number of columns as the
   # number of rows in the right-hand-side matrix
   if [[ "${lhs_dim[1]}" -ne "${rhs_dim[0]}" ]]; then
     echo 'Invalid matrix dimensions. Require M x N times N x K matrices' >&2
-    return 1
+    exit 1
   fi
 
-  declare -A lhs
-  declare -A rhs
+  # use associative arrays as pseudo-multidimensional arrays
+  declare -A lhs  # left-hand-side matrix
+  declare -A rhs  # right-hand-side matrix
+
+  # let lhs matrix has  m  rows and  n  columns
+  # let rhs matrix has  n  rows and  k  columns
   local m="${lhs_dim[0]}"
   local n="${lhs_dim[1]}"
   local k="${rhs_dim[1]}"
@@ -290,31 +348,38 @@ multiply() {
   # read the left-hand-side matrix
   local i=0
   while read row; do
-    row=(${row})
+    row=(${row})  # convert string to array for instant and easy access
+
+    # read each column of the current row to the matrix
     for ((j=0;j<n;j++)); do
       lhs["${i}","${j}"]="${row["${j}"]}"
     done
+
     ((i++))
   done < "$1"
 
   # read the right-hand-side matrix
   i=0
   while read row; do
-    row=(${row})
+    row=(${row})  # convert string to array for instant and easy access
+
+    # read each column of the current row to the matrix
     for ((j=0;j<k;j++)); do
       rhs["${i}","${j}"]="${row["${j}"]}"
     done
+
     ((i++))
   done < "$2"
 
-  # multiply two matrices and print results
+  # multiply two matrices and print results with correct format
   # loop lhs' rows third
   for ((i=0;i<m;i++)); do
     # loop rhs' columns second
     for ((j=0;j<k;j++)); do
       local dot_prod=0
-      # loop lhs' columns of current row and also rhs' rows of current column
+      # loop lhs' columns of current row (and also rhs' rows of current column)
       for ((p=0;p<n;p++)); do
+        # accumulate the dot product
         dot_prod="$(expr "${dot_prod}" + \
           "${lhs["${i}","${p}"]}" \* "${rhs["${p}","${j}"]}")"
       done
@@ -329,9 +394,9 @@ multiply() {
   done
 }
 
+# clean up temporary files on interrupt, hang-up, and termination signals
 trap "rm -f fin$$" INT HUP TERM
 
-# TODO: validate command line arguments and use  $1 "${@:2}"  instead of using case
 case "$1" in
   'dims')
     dims "${@:2}"
@@ -355,7 +420,8 @@ case "$1" in
     echo './matrix mean [MATRIX]' >&2
     echo './matrix add MATRIX_LEFT MATRIX_RIGHT' >&2
     echo './matrix multiply MATRIX_LEFT MATRIX_RIGHT' >&2
+    exit 1
 esac
 
-# clean up
+# clean up temporary files
 rm -f "fin$$"
