Implement dims() for matrix

diff --git a/program1_matrices/matrix b/program1_matrices/matrix
--- a/program1_matrices/matrix
+++ b/program1_matrices/matrix
@@ -12,7 +12,7 @@
 # and all elements are integers.
 #
 # SYNOPSIS
-#   is_valid_matrix matrix
+#   is_int_matrix matrix
 #
 # ARGUMENTS
 #   matrix - a string of EOL-separated rows (to be validated)
@@ -21,31 +21,24 @@
 #   0 - if the  matrix  argument is a valid matrix
 #   1 - otherwise
 is_int_matrix() {
-  # ensure there is a non-empty string to check
-  if [[ "$#" -ne 1 || -z "$1" ]]; then
+  # ensure there is a non-empty and valid filename to check
+  if [[ "$#" -ne 1 ]] || [[ -z "$1" ]] || [[ ! -f "$1" ]]; then
     return 1
   fi
 
-  # get the number of columns in the first row
-  read first_row < "$1"
-  local first_row_arr
-  local num_cols_first_row
-  first_row_arr=(${first_row})
-  num_cols_first_row="${#first_row_arr[@]}"
+  # count the number of rows
+  local num_rows="$(wc -l < "$1")"
+  # count the number of elements
+  local num_elems="$(wc -w < "$1")"
 
-  while read row; do
-    local row_arr
-    local num_cols_row
+  # #elements must be divisible by #rows
+  if [[ "$(expr ${num_elems} % ${num_rows})" -ne 0 ]]; then
+    return 1
+  fi
 
-    # ensure the current row has the same number of elements as the first one
-    row_arr=(${row})
-    num_cols_row="${#row_arr[@]}"
-    if [[ ${num_cols_row} -ne ${num_cols_first_row} ]]; then
-      return 1
-    fi
+  # TODO: Check integers
 
-    # TODO: Check for float and non-numerics (allow integers only). RegEx?
-  done < "$1"
+  return 0
 }
 
 # Prints the dimensions of the matrix as the number of rows, followed by a
@@ -64,47 +57,42 @@ is_int_matrix() {
 dims() {
   # ensure there is at most 1 argument
   if [[ "$#" -gt 1 ]]; then
-    echo -e "Usage: ./matrix dims [matrix]\n" >&2
+    echo 'Usage: ./matrix dims [matrix]' >&2
     return 1
-  
-  # if using file
-  if [[ "$#" -eq 1 ]]; then
-    # ensure the file exists
-    if [ ! -f "$1" ]; then
-      echo -e "Could not read file\n" >&2
-      return 1
-    fi
-    # ensure the matrix is valid
-    if [ ! is_int_matrix "$1" ]; then
-      echo -e "Could not read matrix\n" >&2
-      return 1
-    fi
+  # if using file, ensure the file exists
+  elif [[ "$#" -eq 1 ]] && [[ ! -f "$1" ]]; then
+    echo 'Could not read file' >&2
+    return 1
+  # if no arguments provided
+  # else
+  #   echo 'No arguments provided. Please use stdin'
+  #   use stdin
+  #   while read line; do
+  #     echo "Line is = ${line}"
+  #   done < "${1:-/dev/stdin}"
   fi
 
-  local num_rows
-  local num_cols
-  num_rows=0
-  num_cols=0
+  # validate the matrix
+  if ! is_int_matrix "$1"; then
+    echo 'Invalid matrix' >&2
+    return 1
+  fi
 
   # count the number of rows
-  while read row; do
-    ((num_rows++))
-  done < "$1"
+  local num_rows="$(wc -l < "$1")"
+  # count the number of elements
+  local num_elems="$(wc -w < "$1")"
+  # count the number of columns
+  local num_cols="$(expr ${num_elems} / ${num_rows})"
 
-  # read only the first row of the matrix and count the number of columns
-  read first_row < "$1"
-  for num in ${first_row}; do
-    ((num_cols++))
-  done
-
-  echo -e "${num_rows} ${num_cols}\n"
+  echo "${num_rows} ${num_cols}"
 }
 
 # TODO: validate command line arguments and use  $1 "${@:2}"  instead of using case
 case "$1" in
   dims)
     dims "${@:2}"
-    echo -e "dims() returned $?\n"
+    # echo "dims() returned $?"
     ;;
   *)
     echo 'Invalid operation' >&2
