Implement multiply() function for matrices

diff --git a/program1_matrices/matrix b/program1_matrices/matrix
--- a/program1_matrices/matrix
+++ b/program1_matrices/matrix
@@ -48,8 +48,9 @@ dims() {
   if [[ "$#" -gt 1 ]]; then
     echo 'Usage: ./matrix dims [MATRIX]' >&2
     return 1
+  fi
   # if using file, ensure the file exists
-  elif [[ "$#" -eq 1 ]]; then
+  if [[ "$#" -eq 1 ]]; then
     if [[ ! -f "$1" ]]; then
       echo 'Could not read file' >&2
       return 1
@@ -92,8 +93,9 @@ transpose() {
   if [[ "$#" -gt 1 ]]; then
     echo 'Usage: ./matrix transpose [MATRIX]' >&2
     return 1
+  fi
   # if using file, ensure the file exists
-  elif [[ "$#" -eq 1 ]]; then
+  if [[ "$#" -eq 1 ]]; then
     if [[ ! -f "$1" ]]; then
       echo 'Could not read file' >&2
       return 1
@@ -134,8 +136,9 @@ mean() {
   if [[ "$#" -gt 1 ]]; then
     echo 'Usage: ./matrix mean [MATRIX]' >&2
     return 1
+  fi
   # if using file, ensure the file exists
-  elif [[ "$#" -eq 1 ]]; then
+  if [[ "$#" -eq 1 ]]; then
     if [[ ! -f "$1" ]]; then
       echo 'Could not read file' >& 2
       return 1
@@ -174,7 +177,7 @@ mean() {
 }
 
 # Takes in 2 M-by-N matrices and prints a M-by-N matrix formed by adding the two
-# input matrices
+# input matrices.
 #
 # SYNOPSIS
 #   add MATRIX_LEFT MATRIX_RIGHT
@@ -185,10 +188,6 @@ mean() {
 #   MATRIX_RIGHT - a string of EOL-separated rows, each contains an equal number
 #  of tab-separated integers
 #
-# NOTES
-#   Assume  MATRIX_LEFT  and  MATRIX_RIGHT  have the same number of rows and
-#  the same number of columns.
-#
 # RETURNS
 #   None
 add() {
@@ -196,18 +195,20 @@ add() {
   if [[ "$#" -ne 2 ]]; then
     echo 'Usage: ./matrix add MATRIX_LEFT MATRIX_RIGHT' >&2
     return 1
+  fi
   # ensure the files exist
-  elif [[ ! -f "$1" ]] || [[ ! -f "$2" ]]; then
+  if [[ ! -f "$1" ]] || [[ ! -f "$2" ]]; then
     echo 'Could not read file(s)' >&2
     return 1
+  fi
   # ensure both matrices have the same dimensions
-  elif [[ "$(dims "$1")" != "$(dims "$2")" ]]; then
-    echo 'Invalid matrix summation' >&2
+  if [[ "$(dims "$1")" != "$(dims "$2")" ]]; then
+    echo 'Invalid matrix dimensions. Require two M x N matrices' >&2
     return 1
   fi
 
-  declare -A matleft
-  declare -A matright
+  declare -A lhs
+  declare -A rhs
   local dimensions=($(dims "$1"))
   local num_rows="${dimensions[0]}"
   local num_cols="${dimensions[1]}"
@@ -218,7 +219,7 @@ add() {
     # echo "Row is: ${row}"
     row=(${row})
     for ((j=0;j<num_cols;j++)); do
-      matleft["${i}","${j}"]="${row["${j}"]}"
+      lhs["${i}","${j}"]="${row["${j}"]}"
     done
     ((i++))
   done < "$1"
@@ -228,7 +229,7 @@ add() {
   while read row; do
     row=(${row})
     for ((j=0;j<num_cols;j++)); do
-      matright["${i}","${j}"]="${row["${j}"]}"
+      rhs["${i}","${j}"]="${row["${j}"]}"
     done
     ((i++))
   done < "$2"
@@ -236,12 +237,91 @@ add() {
   # add two matrices and print results
   for ((i=0;i<num_rows;i++)); do
     for ((j=0;j<num_cols;j++)); do
-      local left="${matleft["${i}","${j}"]}"
-      local right="${matright["${i}","${j}"]}"
-
-      printf "%d" "$(expr "${left}" + "${right}")"
+      printf "%d" "$(expr "${lhs["${i}","${j}"]}" + "${rhs["${i}","${j}"]}")"
 
       if [[ "${j}" -lt "$(expr "${num_cols}" - 1)" ]]; then
+        printf "\t"
+      fi
+    done
+    printf "\n"
+  done
+}
+
+# Takes in an M-by-N matrix and an N-by-K matrix and prints a M-by-K matrix
+# formed by multiplying the two input matrices.
+#
+# SYNOPSIS
+#   multiply MATRIX_LEFT MATRIX_RIGHT
+#
+# ARGUMENTS
+#   MATRIX_LEFT - a string of EOL-separated rows, each contains an equal number
+#  of tab-separated integers.
+#   MATRIX_RIGHT - a string of EOL-separated rows, each contains an equal number
+#  of tab-separated integers
+#
+# RETURNS
+#   None
+multiply() {
+  # ensure there are exactly 2 arguments
+  if [[ "$#" -ne 2 ]]; then
+    echo 'Usage: ./matrix multiply MATRIX_LEFT MATRIX_RIGHT' >&2
+    return 1
+  fi
+  # ensure the files exist
+  if [[ ! -f "$1" ]] || [[ ! -f "$2" ]]; then
+    echo 'Could not read file(s)' >&2
+    return 1
+  fi
+  local lhs_dim=($(dims "$1"))
+  local rhs_dim=($(dims "$2"))
+  # ensure the left-hand-side matrix has the same number of columns as the
+  # number of rows in the right-hand-side matrix
+  if [[ "${lhs_dim[1]}" -ne "${rhs_dim[0]}" ]]; then
+    echo 'Invalid matrix dimensions. Require M x N times N x K matrices' >&2
+    return 1
+  fi
+
+  declare -A lhs
+  declare -A rhs
+  local m="${lhs_dim[0]}"
+  local n="${lhs_dim[1]}"
+  local k="${rhs_dim[1]}"
+
+  # read the left-hand-side matrix
+  local i=0
+  while read row; do
+    row=(${row})
+    for ((j=0;j<n;j++)); do
+      lhs["${i}","${j}"]="${row["${j}"]}"
+    done
+    ((i++))
+  done < "$1"
+
+  # read the right-hand-side matrix
+  i=0
+  while read row; do
+    row=(${row})
+    for ((j=0;j<k;j++)); do
+      rhs["${i}","${j}"]="${row["${j}"]}"
+    done
+    ((i++))
+  done < "$2"
+
+  # multiply two matrices and print results
+  # loop lhs' rows third
+  for ((i=0;i<m;i++)); do
+    # loop rhs' columns second
+    for ((j=0;j<k;j++)); do
+      local dot_prod=0
+      # loop lhs' columns of current row and also rhs' rows of current column
+      for ((p=0;p<n;p++)); do
+        dot_prod="$(expr "${dot_prod}" + \
+          "${lhs["${i}","${p}"]}" \* "${rhs["${p}","${j}"]}")"
+      done
+
+      printf "%d" "${dot_prod}"
+
+      if [[ "${j}" -lt "$(expr "${k}" - 1)" ]]; then
         printf "\t"
       fi
     done
@@ -265,8 +345,11 @@ case "$1" in
   'add')
     add "${@:2}"
     ;;
+  'multiply')
+    multiply "${@:2}"
+    ;;
   *)
-    echo 'Invalid argument. Usage:' >&2
+    echo 'Invalid arguments. Usage:' >&2
     echo './matrix dims [MATRIX]' >&2
     echo './matrix transpose [MATRIX]' >&2
     echo './matrix mean [MATRIX]' >&2
